### ISSUE TITLE
No feedback for Elixir test

### ISSUE THREAD

**Issue by aerosol** [rcarriga/vim-ultest#16] opened 2021-03-07 10:52 UTC
**Describe the bug**
No output whatsoever when testing an Elixir ExUnit case.

**To Reproduce**
1. Install elixir (I'm running 1.10.3)
2. Clone https://github.com/aerosol/foo
3. `ULTEST_LOG_LEVEL=DEBUG ULTEST_LOG_FILE=ultest.log nvim test/foo_test.exs`
4. Run `:Ultest`, `:UltestSummaryOpen`

Debug output:
```
 (carb)  /tmp/foo $ tail -f ultest.log
11:43:24 | INFO | MainThread | logging.py:create_logger:71 | Logger created
11:43:24 | DEBUG | MainThread | __init__.py:__init__:40 | Handler created
11:43:33 | DEBUG | Thread-1 | jobs.py:_handle_coroutine:42 | Starting job with group run_all
11:43:33 | INFO | Thread-1 | __init__.py:runner:101 | Running all tests in test/foo_test.exs
11:43:33 | DEBUG | Thread-1 | jobs.py:_handle_coroutine:54 | Finished job with group run_all
```
**Expected behavior**

Any feedback in neovim instance.

**Screenshots**
![screen](https://user-images.githubusercontent.com/173738/110237272-64732d80-7f3b-11eb-8dbd-0c5b2b7c6fe8.png)

**Additional context**

**Comment by rcarriga** [comment] 2021-03-07 11:57
First off, thank you for this report, very easy to reproduce! 

It seems like vim-test doesn't define patterns for individual tests for Elixir. Instead it just sends the test file and the current line as an argument to the test runner. vim-ultest relies on the patterns to find individual tests to be able to use them... Right now this means Elixir will definitely not work.

There are two solutions to this issue
1. The best solution imo is to make a change to vim-test in how it runs tests to use test patterns. It shouldn't be too difficult. All that would be needed is to define a series of patterns to identify elixir tests and then define how to send those test names to the runner inside the runner's `build_position` function.  It looks as though following you'd need runner specific patterns like https://github.com/vim-test/vim-test/blob/master/autoload/test/rust/cargotest.vim.

2. As a workaround, vim-ultest could have the concept of just test files where it has no knowledge of the tests within. The file would always have to run as a whole and the result would be shown as just a passing/failing file in the summary window. I'm not a huge fan of this as it takes away much of the appeal that I see with this plugin but is doable. Might be worthwhile since after digging around I've found that there's a few languages with this problem (clojure, crystal, elixir, elm, lua, perl, racket, viml)

**Comment by rcarriga** [comment] 2021-03-07 12:04
Actually on second thought we likely don't need to have vim-test actually use the patterns. Instead vim-ultest could define the patterns itself for these languages as vim-test seems to rely on line numbers being passed which is already done by vim-ultest

**Comment by aerosol** [comment] 2021-03-07 12:07
Thanks for coming back to me on this one. I'll see if I can fiddle with defining test patterns. Will update here once I have anything meaningful. In the meantime feel free to close this report. Cheers.

**Comment by rcarriga** [comment] 2021-03-07 12:08
I'll leave open for now as there might be more reports of the same with other languages and I'd like to have it all recorded in one place. Once we have a solution I'm happy to close

**Comment by rcarriga** [comment] 2021-03-07 12:15
OK seems to work fine if I define like this
```vim
let test#elixir#patterns = {
  \ 'test':      ['\v^\s*test (".+") do'],
\}
```
Would you mind testing it out as I haven't got the runner actually set up to work.
If it does I'll add a nice way to define them

**Comment by aerosol** [comment] 2021-03-07 12:44
Almost! I'm seeing some logger crashes in the debug log:

```
13:21:13 | ERROR | Thread-1 | logging.py:__deferred_flog:36 | Error converting args to str
Traceback (most recent call last):
  File "/home/hq1/dotfiles/silos/nvim/.config/nvim/bundle/vim-ultest/rplugin/python3/ultest/logging.py", line 33, in __deferred_flog
    level, eval(fstr, frame.f_globals, frame.f_locals), stacklevel=3
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <listcomp>
AttributeError: 'str' object has no attribute 'id'
```

And looks like the feedback is still not quite there yet, I'm getting no errors on failed tests and an empty error floating window on a test that should pass. It's not quite clear when should I expect the test runner to kick in - is it on save?

I tried recording a screencast but the gif turned out 200MB :sweat_smile:, I'll try better later today.

**Comment by aerosol** [comment] 2021-03-07 12:44
What works is the tests are now properly listed in the Summary window.

**Comment by rcarriga** [comment] 2021-03-07 13:20
OK that's a start! You can ignore the logging exception, it's just a bad log message. The empty window probably means the process failed to launch. If you update to the latest version I just pushed I've defined a way to define custom patterns and added the exunit pattern so you can remove the definition I gave you above. 

Try running a test and if it still fails, there'll be a log after you run the test `WARNING | An exception was thrown when starting <test-id> with command: [<command>, ...<args>]` and a stacktrace of what the problem was.  Should give us more info!

Also to answer your question (I think): The runner is only invoked when you manually use the commands to run a test, the tests are already discovered and saved at that point (and refreshed on write of the buffer).

**Comment by aerosol** [comment] 2021-03-07 18:26
@rcarriga it works nicely with the latets patches! :partying_face: many thanks!

**Comment by aerosol** [comment] 2021-03-07 18:35
Testing on a "real" project: it'd be nice to have an option to disable multithreading -- ExUnit takes care of that. So when testing the whole file (I assume that's what happens when `:Ultest` is called), no separate threads should be spawned, otherwise they compete for resource access (such as DB) and clash.

**Comment by rcarriga** [comment] 2021-03-07 20:04
Hmm interesting I'll have to look into it, it should definitely only run only 1 test at a time if you set it. Just to verify it should be `g:ultest_max_threads` (missing a), but I'm assuming that was just a bad paste into GitHub

**Comment by aerosol** [comment] 2021-03-07 21:51
Ah yes, that was a typo, apologies. I'll look into it properly when I get a spare cycle, today wasn't really focused.

**Comment by rcarriga** [comment] 2021-03-08 08:48
No problem at all, I've closed this issue as we've found a solution to the original question but please do open another!

**Closed** 2021-03-08 08:48 UTC
Labels: bug
